### PR TITLE
Hands on - 1

### PR DESCRIPTION
**Pull request by LuciaMm**

### CODE REVIEW

**Comment by rgcmme** [comment]
* You cannot put your files in the root of the HandsOn directory. You have to create a directory for your group following the naming convention given.
* You don't explain why the datasets satisfy the requirements.

**Comment by LuciaMm** [comment]
I think that we solved the problems. Could you check it?

**Comment by rgcmme** [comment]
GroupXX is not "GroupXX" literally; you have to give it a number. For example "Group02" is currently available.

**Comment by LuciaMm** [comment]
Changed it.

**Pull request merged**
