### PR TITLE
HandsOn5 done

### PR DESCRIPTION
**Pull request by mluengo96**

### CODE REVIEW

**Comment by rgcmme** [comment]
* URIs are encoded as strings.
* I don't know why latitud is integer and longitud is double.
* For the different entities, you are creating datatype properties and also object properties. Use only object properties.

**Comment by rgcmme** [comment]
* Some of the previous comments still hold.

**Comment by mluengo96** [comment]
Which ones?

**Comment by mluengo96** [comment]
You're right, we'll fix them today

**Pull request merged**
